
#create_clock -period 20.000 -name clk_25_p -waveform {0.000 10.000} [get_ports I_SYS_50mhz_p]

set_property PACKAGE_PIN P26 [get_ports I_LOC_100mhz]
set_property PACKAGE_PIN G17 [get_ports I_SYS_50mhz_p]
set_property PACKAGE_PIN G16 [get_ports I_SYS_50mhz_n]
set_property PACKAGE_PIN K26 [get_ports O_lmk_resetn]
set_property PACKAGE_PIN G25 [get_ports O_lmk_sel]
set_property PACKAGE_PIN K27 [get_ports O_lmk_sclk]
set_property PACKAGE_PIN J25 [get_ports O_lmk_scs]
set_property PACKAGE_PIN J24 [get_ports O_lmk_sdio]
set_property PACKAGE_PIN G26 [get_ports O_lmk_sync]
set_property PACKAGE_PIN H27 [get_ports I_lmk_st0]
set_property PACKAGE_PIN G27 [get_ports I_lmk_st1]


set_property IOSTANDARD LVCMOS33 [get_ports I_LOC_100mhz]
set_property IOSTANDARD LVDS [get_ports I_SYS_50mhz_p]
set_property IOSTANDARD LVDS [get_ports I_SYS_50mhz_n]
set_property IOSTANDARD LVCMOS33 [get_ports O_lmk_resetn]
set_property IOSTANDARD LVCMOS33 [get_ports O_lmk_sel]
set_property IOSTANDARD LVCMOS33 [get_ports O_lmk_sclk]
set_property IOSTANDARD LVCMOS33 [get_ports O_lmk_scs]
set_property IOSTANDARD LVCMOS33 [get_ports O_lmk_sdio]
set_property IOSTANDARD LVCMOS33 [get_ports O_lmk_sync]
set_property IOSTANDARD LVCMOS33 [get_ports I_lmk_st0]
set_property IOSTANDARD LVCMOS33 [get_ports I_lmk_st1]

set_property IOSTANDARD LVCMOS33 [get_ports I_PXIE_Rst_n]

set_property PACKAGE_PIN L22 [get_ports I_PXIE_Rst_n]

set_property PACKAGE_PIN AB6 [get_ports I_PXIE_Clk_p]
set_property PACKAGE_PIN AB5 [get_ports I_PXIE_Clk_n]


#set_property IOSTANDARD LVCMOS33 [get_ports TXB_AWG1]
#set_property PACKAGE_PIN R18 [get_ports TXB_AWG1]


set_property IOSTANDARD LVDS [get_ports O_Dstarb_p[0]]
set_property IOSTANDARD LVDS [get_ports O_Dstarb_n[0]]
set_property IOSTANDARD LVDS [get_ports O_Dstarb_p[1]]
set_property IOSTANDARD LVDS [get_ports O_Dstarb_n[1]]
set_property IOSTANDARD LVDS [get_ports O_Dstarb_p[2]]
set_property IOSTANDARD LVDS [get_ports O_Dstarb_n[2]]
set_property IOSTANDARD LVDS [get_ports O_Dstarb_p[3]]
set_property IOSTANDARD LVDS [get_ports O_Dstarb_n[3]]
set_property IOSTANDARD LVDS [get_ports O_Dstarb_p[4]]
set_property IOSTANDARD LVDS [get_ports O_Dstarb_n[4]]
set_property IOSTANDARD LVDS [get_ports O_Dstarb_p[5]]
set_property IOSTANDARD LVDS [get_ports O_Dstarb_n[5]]
set_property IOSTANDARD LVDS [get_ports O_Dstarb_p[6]]
set_property IOSTANDARD LVDS [get_ports O_Dstarb_n[6]]
set_property IOSTANDARD LVDS [get_ports O_Dstarb_p[7]]
set_property IOSTANDARD LVDS [get_ports O_Dstarb_n[7]]
set_property IOSTANDARD LVDS [get_ports O_Dstarb_p[8]]
set_property IOSTANDARD LVDS [get_ports O_Dstarb_n[8]]
set_property IOSTANDARD LVDS [get_ports O_Dstarb_p[9]]
set_property IOSTANDARD LVDS [get_ports O_Dstarb_n[9]]
set_property IOSTANDARD LVDS [get_ports O_Dstarb_p[10]]
set_property IOSTANDARD LVDS [get_ports O_Dstarb_n[10]]
set_property IOSTANDARD LVDS [get_ports O_Dstarb_p[11]]
set_property IOSTANDARD LVDS [get_ports O_Dstarb_n[11]]
set_property IOSTANDARD LVDS [get_ports O_Dstarb_p[12]]
set_property IOSTANDARD LVDS [get_ports O_Dstarb_n[12]]
set_property IOSTANDARD LVDS [get_ports O_Dstarb_p[13]]
set_property IOSTANDARD LVDS [get_ports O_Dstarb_n[13]]
set_property IOSTANDARD LVDS [get_ports O_Dstarb_p[14]]
set_property IOSTANDARD LVDS [get_ports O_Dstarb_n[14]]
set_property IOSTANDARD LVDS [get_ports O_Dstarb_p[15]]
set_property IOSTANDARD LVDS [get_ports O_Dstarb_n[15]]
set_property IOSTANDARD LVDS [get_ports O_Dstarb_p[16]]
set_property IOSTANDARD LVDS [get_ports O_Dstarb_n[16]]


set_property PACKAGE_PIN B15 [get_ports O_Dstarb_p[0]]
set_property PACKAGE_PIN A15 [get_ports O_Dstarb_n[0]]
set_property PACKAGE_PIN E16 [get_ports O_Dstarb_p[1]]
set_property PACKAGE_PIN D16 [get_ports O_Dstarb_n[1]]
set_property PACKAGE_PIN D19 [get_ports O_Dstarb_p[2]]
set_property PACKAGE_PIN D18 [get_ports O_Dstarb_n[2]]
set_property PACKAGE_PIN H19 [get_ports O_Dstarb_p[3]]
set_property PACKAGE_PIN H18 [get_ports O_Dstarb_n[3]]
set_property PACKAGE_PIN B20 [get_ports O_Dstarb_p[4]]
set_property PACKAGE_PIN A20 [get_ports O_Dstarb_n[4]]
set_property PACKAGE_PIN C21 [get_ports O_Dstarb_p[5]]
set_property PACKAGE_PIN C22 [get_ports O_Dstarb_n[5]]
set_property PACKAGE_PIN A27 [get_ports O_Dstarb_p[6]]
set_property PACKAGE_PIN A28 [get_ports O_Dstarb_n[6]]
set_property PACKAGE_PIN G20 [get_ports O_Dstarb_p[7]]
set_property PACKAGE_PIN F20 [get_ports O_Dstarb_n[7]]
set_property PACKAGE_PIN D14 [get_ports O_Dstarb_p[8]]
set_property PACKAGE_PIN C14 [get_ports O_Dstarb_n[8]]
set_property PACKAGE_PIN K16 [get_ports O_Dstarb_p[9]]
set_property PACKAGE_PIN J16 [get_ports O_Dstarb_n[9]]
set_property PACKAGE_PIN F18 [get_ports O_Dstarb_p[10]]
set_property PACKAGE_PIN F17 [get_ports O_Dstarb_n[10]]
set_property PACKAGE_PIN L19 [get_ports O_Dstarb_p[11]]
set_property PACKAGE_PIN L18 [get_ports O_Dstarb_n[11]]
set_property PACKAGE_PIN D20 [get_ports O_Dstarb_p[12]]
set_property PACKAGE_PIN D21 [get_ports O_Dstarb_n[12]]
set_property PACKAGE_PIN D24 [get_ports O_Dstarb_p[13]]
set_property PACKAGE_PIN C24 [get_ports O_Dstarb_n[13]]
set_property PACKAGE_PIN C26 [get_ports O_Dstarb_p[14]]
set_property PACKAGE_PIN B26 [get_ports O_Dstarb_n[14]]
set_property PACKAGE_PIN B29 [get_ports O_Dstarb_p[15]]
set_property PACKAGE_PIN A29 [get_ports O_Dstarb_n[15]]
set_property PACKAGE_PIN B24 [get_ports O_Dstarb_p[16]]
set_property PACKAGE_PIN A24 [get_ports O_Dstarb_n[16]]


set_property IOSTANDARD LVDS [get_ports I_Dstarc_p[0]]
set_property IOSTANDARD LVDS [get_ports I_Dstarc_n[0]]
set_property IOSTANDARD LVDS [get_ports I_Dstarc_p[1]]
set_property IOSTANDARD LVDS [get_ports I_Dstarc_n[1]]
set_property IOSTANDARD LVDS [get_ports I_Dstarc_p[2]]
set_property IOSTANDARD LVDS [get_ports I_Dstarc_n[2]]
set_property IOSTANDARD LVDS [get_ports I_Dstarc_p[3]]
set_property IOSTANDARD LVDS [get_ports I_Dstarc_n[3]]
set_property IOSTANDARD LVDS [get_ports I_Dstarc_p[4]]
set_property IOSTANDARD LVDS [get_ports I_Dstarc_n[4]]
set_property IOSTANDARD LVDS [get_ports I_Dstarc_p[5]]
set_property IOSTANDARD LVDS [get_ports I_Dstarc_n[5]]
set_property IOSTANDARD LVDS [get_ports I_Dstarc_p[6]]
set_property IOSTANDARD LVDS [get_ports I_Dstarc_n[6]]
set_property IOSTANDARD LVDS [get_ports I_Dstarc_p[7]]
set_property IOSTANDARD LVDS [get_ports I_Dstarc_n[7]]
set_property IOSTANDARD LVDS [get_ports I_Dstarc_p[8]]
set_property IOSTANDARD LVDS [get_ports I_Dstarc_n[8]]
set_property IOSTANDARD LVDS [get_ports I_Dstarc_p[9]]
set_property IOSTANDARD LVDS [get_ports I_Dstarc_n[9]]
set_property IOSTANDARD LVDS [get_ports I_Dstarc_p[10]]
set_property IOSTANDARD LVDS [get_ports I_Dstarc_n[10]]
set_property IOSTANDARD LVDS [get_ports I_Dstarc_p[11]]
set_property IOSTANDARD LVDS [get_ports I_Dstarc_n[11]]
set_property IOSTANDARD LVDS [get_ports I_Dstarc_p[12]]
set_property IOSTANDARD LVDS [get_ports I_Dstarc_n[12]]
set_property IOSTANDARD LVDS [get_ports I_Dstarc_p[13]]
set_property IOSTANDARD LVDS [get_ports I_Dstarc_n[13]]
set_property IOSTANDARD LVDS [get_ports I_Dstarc_p[14]]
set_property IOSTANDARD LVDS [get_ports I_Dstarc_n[14]]
set_property IOSTANDARD LVDS [get_ports I_Dstarc_p[15]]
set_property IOSTANDARD LVDS [get_ports I_Dstarc_n[15]]
set_property IOSTANDARD LVDS [get_ports I_Dstarc_p[16]]
set_property IOSTANDARD LVDS [get_ports I_Dstarc_n[16]]


set_property PACKAGE_PIN B14 [get_ports I_Dstarc_p[0]]
set_property PACKAGE_PIN A14 [get_ports I_Dstarc_n[0]]
set_property PACKAGE_PIN H17 [get_ports I_Dstarc_p[1]]
set_property PACKAGE_PIN H16 [get_ports I_Dstarc_n[1]]
set_property PACKAGE_PIN K18 [get_ports I_Dstarc_p[2]]
set_property PACKAGE_PIN K17 [get_ports I_Dstarc_n[2]]
set_property PACKAGE_PIN C18 [get_ports I_Dstarc_p[3]]
set_property PACKAGE_PIN C17 [get_ports I_Dstarc_n[3]]
set_property PACKAGE_PIN C19 [get_ports I_Dstarc_p[4]]
set_property PACKAGE_PIN B19 [get_ports I_Dstarc_n[4]]
set_property PACKAGE_PIN B21 [get_ports I_Dstarc_p[5]]
set_property PACKAGE_PIN B22 [get_ports I_Dstarc_n[5]]
set_property PACKAGE_PIN C27 [get_ports I_Dstarc_p[6]]
set_property PACKAGE_PIN B27 [get_ports I_Dstarc_n[6]]
set_property PACKAGE_PIN A19 [get_ports I_Dstarc_p[7]]
set_property PACKAGE_PIN A18 [get_ports I_Dstarc_n[7]]
set_property PACKAGE_PIN L15 [get_ports I_Dstarc_p[8]]
set_property PACKAGE_PIN K15 [get_ports I_Dstarc_n[8]]
set_property PACKAGE_PIN E15 [get_ports I_Dstarc_p[9]]
set_property PACKAGE_PIN D15 [get_ports I_Dstarc_n[9]]
set_property PACKAGE_PIN B17 [get_ports I_Dstarc_p[10]]
set_property PACKAGE_PIN B16 [get_ports I_Dstarc_n[10]]
set_property PACKAGE_PIN E18 [get_ports I_Dstarc_p[11]]
set_property PACKAGE_PIN E17 [get_ports I_Dstarc_n[11]]
set_property PACKAGE_PIN G19 [get_ports I_Dstarc_p[12]]
set_property PACKAGE_PIN F19 [get_ports I_Dstarc_n[12]]
set_property PACKAGE_PIN E20 [get_ports I_Dstarc_p[13]]
set_property PACKAGE_PIN E21 [get_ports I_Dstarc_n[13]]
set_property PACKAGE_PIN B25 [get_ports I_Dstarc_p[14]]
set_property PACKAGE_PIN A25 [get_ports I_Dstarc_n[14]]
set_property PACKAGE_PIN D28 [get_ports I_Dstarc_p[15]]
set_property PACKAGE_PIN C28 [get_ports I_Dstarc_n[15]]
set_property PACKAGE_PIN J19 [get_ports I_Dstarc_p[16]]
set_property PACKAGE_PIN J18 [get_ports I_Dstarc_n[16]]


set_property IOSTANDARD LVCMOS33 [get_ports O_star[0]]
set_property IOSTANDARD LVCMOS33 [get_ports O_star[1]]
set_property IOSTANDARD LVCMOS33 [get_ports O_star[2]]
set_property IOSTANDARD LVCMOS33 [get_ports O_star[3]]
set_property IOSTANDARD LVCMOS33 [get_ports O_star[4]]
set_property IOSTANDARD LVCMOS33 [get_ports O_star[5]]
set_property IOSTANDARD LVCMOS33 [get_ports O_star[6]]
set_property IOSTANDARD LVCMOS33 [get_ports O_star[7]]
set_property IOSTANDARD LVCMOS33 [get_ports O_star[8]]
set_property IOSTANDARD LVCMOS33 [get_ports O_star[9]]
set_property IOSTANDARD LVCMOS33 [get_ports O_star[10]]
set_property IOSTANDARD LVCMOS33 [get_ports O_star[11]]
set_property IOSTANDARD LVCMOS33 [get_ports O_star[12]]
set_property IOSTANDARD LVCMOS33 [get_ports O_star[13]]
set_property IOSTANDARD LVCMOS33 [get_ports O_star[14]]
set_property IOSTANDARD LVCMOS33 [get_ports O_star[15]]
set_property IOSTANDARD LVCMOS33 [get_ports O_star[16]]
set_property IOSTANDARD LVCMOS33 [get_ports O_trigger ]

set_property PACKAGE_PIN P20 [get_ports O_star[0]]
set_property PACKAGE_PIN M20 [get_ports O_star[1]]
set_property PACKAGE_PIN L20 [get_ports O_star[2]]
set_property PACKAGE_PIN M21 [get_ports O_star[3]]
set_property PACKAGE_PIN N21 [get_ports O_star[4]]
set_property PACKAGE_PIN K20 [get_ports O_star[5]]
set_property PACKAGE_PIN K21 [get_ports O_star[6]]
set_property PACKAGE_PIN M22 [get_ports O_star[7]]
set_property PACKAGE_PIN N22 [get_ports O_star[8]]
set_property PACKAGE_PIN P23 [get_ports O_star[9]]
set_property PACKAGE_PIN R23 [get_ports O_star[10]]
set_property PACKAGE_PIN T24 [get_ports O_star[11]]
set_property PACKAGE_PIN R25 [get_ports O_star[12]]
set_property PACKAGE_PIN T25 [get_ports O_star[13]]
set_property PACKAGE_PIN R26 [get_ports O_star[14]]
set_property PACKAGE_PIN R27 [get_ports O_star[15]]
set_property PACKAGE_PIN T27 [get_ports O_star[16]]
set_property PACKAGE_PIN L27 [get_ports O_trigger ]

set_property BITSTREAM.CONFIG.CONFIGRATE 50 [current_design]